### ISSUE TITLE
[Question] flushModuleIds vs flushChunkNames

### ISSUE THREAD

**Issue by aga5tya** [chrisblossom/react-universal-starter#1]
Hi @chrisblossom , Just a query, When webpack.HashedModuleIdsPlugin() is used in production, shouldn't flushModuleIds be used instead of flushChunkNames be used from react-universal-component/server when server is running in production?

Referrering to this,
https://github.com/chrisblossom/react-universal-starter/blob/master/src/server.js#L83

**Comment by aga5tya** [comment]
This is how i am doing it, and seems to work just fine.

```js
import {
    flushChunkNames,
    flushModuleIds
} from 'react-universal-component/server'
import flushChunks from 'webpack-flush-chunks'

const { scripts, stylesheets, publicPath } = flushChunks(clientEntryStats, {
    ...(process.env.NODE_ENV === 'production'
        ? { moduleIds: flushModuleIds() }
        : { chunkNames: flushChunkNames() }),
    before: ['bootstrap'],
    after: ['app']
})
```

**Comment by chrisblossom** [comment]
In regards to ``react-universal-component ``, it is recommended to use ``chunkNames`` over ``moduleIds`` because ``webpack-flush-chunks`` has to do less work server-side to flush the necessary chunks. I do not think this should change if you are using ``HashedModuleIdsPlugin`` or ``NamedModulesPlugin``. 

@faceyspacey please confirm.

See https://github.com/webpack/webpack.js.org/issues/652 for a guide when to use ``HashedModuleIdsPlugin`` or ``NamedModulesPlugin``

**Comment by faceyspacey** [comment]
yea, chunkNames is faster. But there may be another reason to use moduleIds in the future. Chunk names are challenging when it comes to dynamic requires, and I'm not sure webpack got it fully right.

...if ur using chunk names u dont need to make ur module ids deterministic.

**Comment by aga5tya** [comment]
@faceyspacey @chrisblossom,
That ideally means i can use either of those plugins and still use ```flushChunkNames()```, if im not wrong?

Also, Wouldn't you recommend using NamedModulesPlugin on both development and production for any reason?

https://medium.com/@mikegreiling/shouldnt-we-prefer-to-use-hashedmoduleidsplugin-over-namedmodulesplugin-in-production-c01329cf787a

**Comment by chrisblossom** [comment]
Yes, you can use either plugin with ``flushChunkNames``.

I do not know enough about the ``NamedModulesPlugin`` / ``HashedModuleIdsPlugin`` plugins to answer your question. From the issue I linked above, I gathered it was recommended to use ``NamedModulesPlugin`` in development and ``HashedModuleIdsPlugin`` in production. I didn't spend too much time on it and could definitely have misunderstood what was being said.

If you find a definite answer please share!

**Comment by aga5tya** [comment]
Awesome, It works just fine :) Thank you @chrisblossom. I'l be sure to update here in case i get more clarity on this topic.
