### ISSUE TITLE
create readme and add note about providing ur own AUTH_TOKEN

### ISSUE THREAD

**Issue by faceyspacey** [chrisblossom/react-universal-starter#2]
i just pasted mine from `/.npmrc` . not sure if that's the idiomatic way.

...but people like this, u should help them get started

**Comment by chrisblossom** [comment]
This is used for private NPM packages. I removed the ``NPM_TOKEN`` requirement and the ``redis-server``, both which required external setup. https://github.com/chrisblossom/react-universal-starter/commit/0147135d452479a951e23e529e00219aeb1348d6
